import { auth } from "@/lib/auth-server";
import { successResponse, errorResponse } from "@/lib/api-response";

const teamsData = [
  {
    id: 1,
    name: "Engineering",
    members: 128,
    icon: "Users",
    iconBg: "#eff6ff",
    iconColor: "#3b82f6",
    health: 92,
    healthColor: "#10b981",
    collab: "Excellent",
    know: 96,
    knowColor: "#10b981",
    actions: 342,
    actionsTrend: 18,
    focus: "Productivity",
    focusBg: "#f5f3ff",
    focusColor: "#8b5cf6",
    isUp: true,
  },
  {
    id: 2,
    name: "Product",
    members: 64,
    icon: "BarChart2",
    iconBg: "#eff6ff",
    iconColor: "#3b82f6",
    health: 88,
    healthColor: "#10b981",
    collab: "Good",
    know: 93,
    knowColor: "#10b981",
    actions: 221,
    actionsTrend: 12,
    focus: "Roadmap",
    focusBg: "#eff6ff",
    focusColor: "#3b82f6",
    isUp: true,
  },
  {
    id: 3,
    name: "Sales",
    members: 96,
    icon: "Target",
    iconBg: "#f0fdf4",
    iconColor: "#16a34a",
    health: 85,
    healthColor: "#10b981",
    collab: "Good",
    know: 90,
    knowColor: "#10b981",
    actions: 184,
    actionsTrend: 15,
    focus: "Pipeline",
    focusBg: "#f0fdf4",
    focusColor: "#16a34a",
    isUp: true,
  },
  {
    id: 4,
    name: "Marketing",
    members: 48,
    icon: "Users",
    iconBg: "#fef2f2",
    iconColor: "#ef4444",
    health: 78,
    healthColor: "#f59e0b",
    collab: "Fair",
    know: 85,
    knowColor: "#10b981",
    actions: 132,
    actionsTrend: 8,
    focus: "Campaigns",
    focusBg: "#fff3ee",
    focusColor: "#ff6b00",
    isUp: true,
  },
  {
    id: 5,
    name: "Customer Success",
    members: 52,
    icon: "Activity",
    iconBg: "#eff6ff",
    iconColor: "#3b82f6",
    health: 75,
    healthColor: "#f59e0b",
    collab: "Fair",
    know: 83,
    knowColor: "#10b981",
    actions: 98,
    actionsTrend: 5,
    focus: "Retention",
    focusBg: "#fffbeb",
    focusColor: "#d97706",
    isUp: true,
  },
  {
    id: 6,
    name: "Finance",
    members: 36,
    icon: "Target",
    iconBg: "#fffbeb",
    iconColor: "#d97706",
    health: 72,
    healthColor: "#f59e0b",
    collab: "Fair",
    know: 80,
    knowColor: "#f59e0b",
    actions: 76,
    actionsTrend: -2,
    focus: "Reporting",
    focusBg: "#f5f3ff",
    focusColor: "#8b5cf6",
    isUp: false,
  },
  {
    id: 7,
    name: "People Operations",
    members: 28,
    icon: "Users",
    iconBg: "#fff3ee",
    iconColor: "#ff6b00",
    health: 68,
    healthColor: "#ff6b00",
    collab: "Needs attention",
    know: 74,
    knowColor: "#f59e0b",
    actions: 64,
    actionsTrend: -4,
    focus: "HR Systems",
    focusBg: "#fef2f2",
    focusColor: "#ef4444",
    isUp: false,
  },
  {
    id: 8,
    name: "Legal",
    members: 15,
    icon: "ShieldAlert",
    iconBg: "#fef2f2",
    iconColor: "#ef4444",
    health: 60,
    healthColor: "#ef4444",
    collab: "Poor",
    know: 62,
    knowColor: "#ef4444",
    actions: 31,
    actionsTrend: -6,
    focus: "Compliance",
    focusBg: "#fef2f2",
    focusColor: "#ef4444",
    isUp: false,
  },
];

export async function GET() {
  try {
    await auth(); // Enforce authentication

    // Simulate network delay
    await new Promise((resolve) => setTimeout(resolve, 800));
    return successResponse(teamsData);
  } catch (error) {
    if (error instanceof Error && error.message === "Unauthorized") return errorResponse("Unauthorized", 401);
    console.error("GET /api/teams error:", error);
    return errorResponse("Internal Server Error", 500);
  }
}
